config/routes.rb
Rails.application.routes.draw do
  resources :words
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "word#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/word.rb
class Word < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/words_controller.rb
require 'uri'
require 'net/http'
require 'json'
class WordsController < ApplicationController
  before_action :set_word, only: %i[show edit update destroy]

  # GET /words or /words.json
  def index
    @word = Word.new
    @words = Word.all
  end

  # GET /words/1 or /words/1.json
  def show
    key = Word.last['word_name']
   
    url = URI("https://api.dictionaryapi.dev/api/v2/entries/en/#{key}")

    https = Net::HTTP.new(url.host, url.port)
    https.use_ssl = true

    request = Net::HTTP::Get.new(url)

    response = https.request(request)

    @output = response.read_body

    result = JSON.parse(@output)
    @sv1 = result[0]['meanings']
    @sv2 = @sv1[0]['definitions']
    @sv3 = @sv2[0]['definition']
    @mp3=result[0]['phonetics']
    @x=@mp3[1]['audio']
  end

  # GET /words/new
  def new
    @word = Word.new
  end

  # GET /words/1/edit
  def edit; end

  # POST /words or /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to word_url(@word), notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1 or /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to word_url(@word), notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1 or /words/1.json
  def destroy
    @word.destroy

    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_word
    @word = Word.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def word_params
    params.require(:word).permit(:word_name, :word_def)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DictionaryApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/words/_form.html.erb
<h1>Dictionary App</h1>

<%= form_with(model: word) do |form| %>
  <% if word.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
        <% word.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :word_name, style: "display: block" %>
    <%= form.text_field :word_name %>
  </div>

 

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/words/_word.html.erb
<div id="<%= dom_id word %>">
  <p>
    <strong>Word name:</strong>
    <%= word.word_name %>
  </p>

  <p>
    <strong>Word definition:</strong>
    <%= @sv3  %>
  </p>
 <p>
    <strong>listen Audio:</strong>
    <%=  link_to "click here",@x %>
  </p>

  


</div>

app/views/words/edit.html.erb
<h1>Editing word</h1>

<%= render "form", word: @word %>

<br>

<div>
  <%= link_to "Show this word", @word %> |
  <%= link_to "Back to words", words_path %>
</div>

app/views/words/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Words</h1>

<div id="words">
  <% @words.each do |word| %>
    <%= render word %>
    <p>
      <%= link_to "Show this word", word %>
    </p>
  <% end %>
</div>

<%= link_to "New word", new_word_path %>

app/views/words/new.html.erb
<h1>New word</h1>

<%= render "form", word: @word %>

<br>

<div>
  <%= link_to "Back to words", words_path %>
</div>

app/views/words/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @word %>

<div>
  <%= link_to "Edit this word", edit_word_path(@word) %> |
  <%= link_to "Back to words", words_path %>

  <%= button_to "Destroy this word", @word, method: :delete %>
</div>